---

repos:
  - repo: local
    hooks:
      - id: ktlint
        name: Lint Kotlin
        entry: ktlint
        language: system
        types: [kotlin]
        stages: [pre-commit]

      - id: actionlint
        name: Lint GitHub Actions workflows
        entry: actionlint
        language: system
        files: '^\.github/workflows/'
        stages: [pre-commit]

      - id: yamllint
        name: Lint YAML
        entry: yamllint
        language: system
        types: [yaml]
        stages: [pre-commit]

      - id: markdownlint
        name: Lint markdown
        entry: markdownlint-cli2
        language: system
        types: [markdown]
        stages: [pre-commit]
