[tools]
java = "corretto-21"
pre-commit = "4.6.0"
markdownlint-cli2 = "0.22.1"
actionlint = "1.7.12"
ktlint = "1.8.0"
git-cliff = "2.13.1"
pipx = "1.14.0"
"pipx:yamllint" = "1.38.0"

[settings]
experimental = true

[task_config]
includes = [
    ".mise/pre-commit.toml",
]