---
tasks:
  generateOpenAPI:
    action: !io.gitlab.curs3w4ll.openapi.generator.kotlintoolchain.plugin.openApiGenerate
      inputSpec: ${module.rootDir}/${pluginSettings.inputSpec}
      outputDir: ${taskOutputDir}
      generatorName: ${pluginSettings.generatorName}
      verbose: ${pluginSettings.verbose}
      logToStderr: ${pluginSettings.logToStderr}
      dryRun: ${pluginSettings.dryRun}
      validateSpec: ${pluginSettings.validateSpec}
      skipValidateSpec: ${pluginSettings.skipValidateSpec}
      cleanupOutput: ${pluginSettings.cleanupOutput}
      globalProperties: ${pluginSettings.globalProperties}
      configOptions: ${pluginSettings.configOptions}
      additionalProperties: ${pluginSettings.additionalProperties}
      packageName: ${pluginSettings.packageName}
      apiPackage: ${pluginSettings.apiPackage}
      modelPackage: ${pluginSettings.modelPackage}
      invokerPackage: ${pluginSettings.invokerPackage}
      modelNamePrefix: ${pluginSettings.modelNamePrefix}
      modelNameSuffix: ${pluginSettings.modelNameSuffix}
      apiNameSuffix: ${pluginSettings.apiNameSuffix}
      groupId: ${pluginSettings.groupId}
      id: ${pluginSettings.id}
      version: ${pluginSettings.version}
      library: ${pluginSettings.library}
      gitHost: ${pluginSettings.gitHost}
      gitUserId: ${pluginSettings.gitUserId}
      gitRepoId: ${pluginSettings.gitRepoId}
      releaseNote: ${pluginSettings.releaseNote}
      typeMappings: ${pluginSettings.typeMappings}
      instantiationTypes: ${pluginSettings.instantiationTypes}
      importMappings: ${pluginSettings.importMappings}
      languageSpecificPrimitives: ${pluginSettings.languageSpecificPrimitives}
      nameMappings: ${pluginSettings.nameMappings}
      parameterNameMappings: ${pluginSettings.parameterNameMappings}
      modelNameMappings: ${pluginSettings.modelNameMappings}
      enumNameMappings: ${pluginSettings.enumNameMappings}
      operationIdNameMappings: ${pluginSettings.operationIdNameMappings}

generated:
  sources:
    - language: kotlin
      directory: ${tasks.generateOpenAPI.action.outputDir}
