---
tasks:
  generateOpenAPI:
    action: !io.gitlab.curs3w4ll.openapi.generator.kotlintoolchain.plugin.openApiGenerate
      inputSpec: ${module.rootDir}/${pluginSettings.inputSpec}
      outputDir: ${taskOutputDir}
      generatorName: ${pluginSettings.generatorName}
      verbose: ${pluginSettings.verbose}
      logToStderr: ${pluginSettings.logToStderr}
      dryRun: ${pluginSettings.dryRun}
      configOptions: ${pluginSettings.configOptions}
      packageName: ${pluginSettings.packageName}
      apiPackage: ${pluginSettings.apiPackage}
      modelPackage: ${pluginSettings.modelPackage}
      invokerPackage: ${pluginSettings.invokerPackage}
      modelNamePrefix: ${pluginSettings.modelNamePrefix}
      modelNameSuffix: ${pluginSettings.modelNameSuffix}
      apiNameSuffix: ${pluginSettings.apiNameSuffix}
      groupId: ${pluginSettings.groupId}
      id: ${pluginSettings.id}
      version: ${pluginSettings.version}

generated:
  sources:
    - language: kotlin
      directory: ${tasks.generateOpenAPI.action.outputDir}
