---

lint:
  stage: lint
  needs: []
  extends:
    - .default-retry
    - .default-before_script
    - .interruptible
  cache:
    - !reference [".mise-cache", cache]
    - !reference [".pre-commit-cache", cache]
  rules:
    - !reference [".if-merge-request", rules]
    - !reference [".if-default-branch", rules]
  script:
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        mise run pre-commit:run -- "$CI_MERGE_REQUEST_DIFF_BASE_SHA" "$CI_COMMIT_SHA"
      else
        mise run pre-commit:run
      fi
